config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/index'

  #get 'newdeposit', to: 'users#newdeposit'
  
  post 'users/addmoney'
  
  devise_for :users
  resources :users, only: [:index, :show]


  root 'static_pages#index'

  #get 'users/profile', as: 'user_root'

  resources :predictions, only: [:index, :new, :create, :destroy]
  resources :subscriptions, only: [:index, :new, :create, :destroy]

  get 'statistic', to: 'predictions#statistic'
  get 'predictions/:id', to: 'predictions#purchase'
  get 'predictions/:id/accept', to: 'predictions#accept'
  get 'predictions/:id/decline', to: 'predictions#decline'
  get 'subscriptions/:id', to: 'subscriptions#purchase'

  get 'cpvls', to: 'users#panel'

  get 'faq', to: 'static_pages#faq'
  get 'contact', to: 'static_pages#contact'

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
	has_many :purchases
	has_many :users, through: :purchases

	def self.prediction_purchase(prediction, current_user)
    price = calculate_price(current_user)
	  if current_user.balance >= price
      current_user.balance -= price

      purchase = Purchase.new user_id: current_user.id, prediction_id: prediction.id, price: price
      
      purchase.save
      #current_user.predictions << prediction

      current_user.save ? true : false
    else
      false
    end
	end

  def self.calculate_price(current_user)
    count = current_user.purchases.where({created_at: Time.now.midnight..(Time.now.midnight + 1.day) }).count
    purchases_count = count % 3
    case purchases_count
      when 0
        return 300
      when 1
        return 200
      when 2
        return 100
      else
        return 300
    end
  end

end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
    include ApplicationHelper
	before_action :authenticate_user!, except: [:statistic]
  before_action :check_if_admin, only: [:new, :create, :accept, :decline]

	def index
#    @count_of_purchases = current_user.purchases.where({created_at: Time.now.midnight..(Time.now.midnight + 1.day) }).count
		if current_user.is_admin?
      @admin = true
    else
      @admin = false
    end

    if (Subscription.subscribed?(current_user))
    if (Subscription.subscribed?(current_user) > Time.now)
      @subscribed = Subscription.subscribed?(current_user) 
      end
    end
    @calculated_price = Prediction.calculate_price(current_user)
    @predictions = Prediction.where(status: "")
	end

  def statistic
    @predictions = Prediction.where.not(status: "")
  end

  def accept
    prediction = Prediction.find(params[:id])
    prediction.status = "win"
    prediction.save
    redirect_to predictions_path
  end

  def decline
    prediction = Prediction.find(params[:id])
    prediction.status = "lose"
    prediction.save
    prediction.purchases.each do |f|
      user = User.find(f.user_id)
      user.balance += f.price
      user.save
    end
    redirect_to predictions_path
  end

	def new
		@prediction = Prediction.new
	end

	def create
		@prediction = Prediction.new(prediction_params)
	  if @prediction.save
      flash[:success] =  'Прогноз был успешно добавлен'
   		redirect_to action: 'index'
  	else
      flash[:danger] = 'Возникла ошибка'
      render :new
  	end
  end

    def purchase
=begin
      @prediction = Prediction.find_by_id(params[:id])
  		if current_user.balance >= @prediction.price
  			current_user.balance -= @prediction.price
        current_user.predictions << @prediction
  			if current_user.save
          flash[:success] = 'Прогноз успешно куплен'
  				redirect_to action: 'index'
  			end
  		else
        flash[:danger] = 'Недостаточно средств на балансе для покупки этого прогноза'
  			redirect_to action: 'index'
  		end
=end

      prediction = Prediction.find_by_id(params[:id])
      if Prediction.prediction_purchase(prediction, current_user)
        flash[:success] = 'Прогноз успешно куплен'
        redirect_to action: 'index'
      else
        flash[:danger] = 'Недостаточно средств на балансе для покупки этого прогноза'
        redirect_to action: 'index'
      end

    end

    def destroy
        @prediction = Prediction.find(params[:id]).destroy
        redirect_to action: 'index'
    end


	private
	def prediction_params
      params.require(:prediction).permit(:discipline, :info, :date, :price, :status)
  end

#  def calculate_purchases
#    current_user.purchases.where({created_at: Time.now.midnight..(Time.now.midnight + 1.day) }).count
#  end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<%= form_for(@prediction) do |f| %>
  <% if @prediction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
      <% @prediction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :discipline %><br>
    <%= f.text_field :discipline %>
  </div>
  <div class="field">
    <%= f.label :bettype %><br>
    <%= f.text_field :bettype %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_local_field :date %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %></br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/predictions/index.html.erb
<h1>List of predictions</h1>

<div class="table-responsive">          
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Sport</th>
        <th>Prediction</th>
        <th>Date of match</th>
        <th>Time of match</th>
        <th>Price</th>
        <th>Purchase</th>
        <% if @admin %><th>Status</th><% end %>
      </tr>
    </thead>
    <tbody>
        <% @predictions.each do |prediction| %>

        <% if current_user.predictions.where(id: prediction).any? %> 
            <% owned = true %> 
        <% else %> 
            <% owned = false %>
        <% end %>

      <tr>
        <td><%= prediction.discipline %></td>
        <td><% if owned || @subscribed %> <%= prediction.info %> <% else %> To access need to buy. <% end %></td>
        <td><%= prediction.date.strftime("%d.%m.%y") %></td>
        <td><%= prediction.date.strftime("%H:%M") %></td>
        <td><% if owned || @subscribed %> - <% else %><%= @calculated_price.round.to_s + " BM" %><% end %></td>
        <!--<td><%= prediction.status %></td>-->
        <td>
        <% if owned  || @subscribed %> 
          Bought 
        <% else %>
          <%= link_to 'Buy', prediction, data: { confirm: 'Are you sure that you want to buy this prediction? ' } %>
        <% end %>
        </td>
        <% if @admin %>
          <td><%= link_to 'Success', {action: :accept, id: prediction}, class: 'green' %><br>
          <%= link_to 'Fail', {action: :decline, id: prediction}, class: 'red' %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <br>

<!-- <%= link_to 'Добавить прогноз', new_prediction_path %> -->

app/views/predictions/new.html.erb
<h1>New prediction</h1>

<%= render 'form' %>

<%= link_to 'Back', predictions_path %>

app/views/predictions/statistic.html.erb
<h1>Statistic of predictions</h1>

<div class="table-responsive">          
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Sport</th>
        <th>Prediction</th>
        <th>Date of match</th>
        <th>Time of match</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
        <% @predictions.each do |prediction| %>
        <% if prediction.status == "win" %>
          <% status = "Success" %>
          <% color = "green" %>
        <% end %>
        <% if prediction.status == "lose" %>
          <% status = "Fail" %>
          <% color = "red" %>
        <% end %> 
      <tr>
        <td><%= prediction.discipline %></td>
        <td><%= prediction.info %></td>
        <td><%= prediction.date.strftime("%d.%m.%y") %></td>
        <td><%= prediction.date.strftime("%H:%M") %></td>
        <td style="color: <%= color %>"><%= status %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <br>