config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/index'

  #get 'newdeposit', to: 'users#newdeposit'
  
  post 'users/addmoney'
  
  devise_for :users
  resources :users, only: [:index, :show]


  root 'static_pages#index'

  #get 'users/profile', as: 'user_root'

  resources :predictions, only: [:index, :new, :create, :destroy]
  resources :subscriptions, only: [:index, :new, :create, :destroy]

  get 'statistic', to: 'predictions#statistic'
  get 'predictions/:id', to: 'predictions#purchase'
  get 'predictions/:id/accept', to: 'predictions#accept'
  get 'predictions/:id/decline', to: 'predictions#decline'
  get 'subscriptions/:id', to: 'subscriptions#purchase'

  get 'cpvls', to: 'users#panel'

  get 'faq', to: 'static_pages#faq'
  get 'contact', to: 'static_pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :purchases
  has_many :predictions, through: :purchases

  has_many :subscribes
  has_many :subscriptions, through: :subscribes

	validates :terms, :acceptance => true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable
         #:confirmable



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :user_signed_in?
  before_action :check_if_admin, only: [:index, :panel, :show, :addmoney]


  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def panel
  end

  def addmoney
    user = User.find_by_id(params[:id])
    user.balance += params[:amount].to_f
    user.save
    redirect_to user
  end

  def profile
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
Общее количество пользователей в базе данных: <%= @users.count %>
<hr>
<% @users.each do |f| %>
    <p><b>ID:</b> <%= f.id %> 
    <br>
    <b>Email:</b> <%= f.email %> 
    <br>
    <b>Имя:</b> <%= f.name %> <b>Фамилия:</b>  <%= f.surname %>
    <br>
    <b>Баланс:</b> <%= f.balance.round %> BM
    <br>
    <b>Бонусный счет:</b> 
    <br> 
    <%= link_to 'ССЫЛКА НА ПРОФИЛЬ', f %></p>
<hr>
<% end %>

app/views/users/newdeposit.html.erb
<%= form_tag({action: 'createdeposit'}) do %>
  <p>
  <%= label_tag :userstoadd, 'Пользователь' %><br>
      <%= select_tag(:userstoadd, User.all.collect {|p| [ p.email, p.id ] })%>
      </p>
      <select><option>1</option></select>
  <p> <%= label_tag :amount, 'Сумма' %>
      <%= text_field_tag :amount %>
  </p>
  <p><%= submit_tag 'Добавить средства' %></p>
<% end %>

app/views/users/panel.html.erb
<%= link_to 'Список пользователей', users_path %>

app/views/users/profile.html.erb
profile
<br />
<%= current_user.name %><br />
<%= current_user.surname %><br />
<%= current_user.birthday < Date.new(1998,current_user.birthday.month,current_user.birthday.day) %><br />
<%= current_user.birthday.day %> - <%= current_user.birthday.month %> - <%= current_user.birthday.year %>

app/views/users/show.html.erb
<% if user_signed_in? %>
    <% if @user == current_user || current_user.is_admin? %>
        <ul class="list-unstyled">
          <li>id: <%= @user.id %></li>
          <li>email: <%= @user.email %></li>
          <li>name: <%= @user.name %></li>
          <li>surname: <%= @user.surname %></li>
          <li>balance: <%= @user.balance %></li>

        </ul>
    <% end %>

    <% if current_user.is_admin? %>

    	<h2>Добавление средств на счет</h2>
        <%= form_tag action: "addmoney", id: @user do %>
          <p><%= label_tag :amount, "Сумма: " %>
          <%= text_field_tag :amount %></p>
          <p><%= submit_tag "Добавить средства" %>
        <% end %>

        <p><%= link_to 'Назад к списку пользователей', users_path %></p>
    <% end %>
<% end %>