config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/index'

  #get 'newdeposit', to: 'users#newdeposit'
  
  post 'users/addmoney'
  
  devise_for :users
  resources :users, only: [:index, :show]


  root 'static_pages#index'

  #get 'users/profile', as: 'user_root'

  resources :predictions, only: [:index, :new, :create, :destroy]
  resources :subscriptions, only: [:index, :new, :create, :destroy]

  get 'statistic', to: 'predictions#statistic'
  get 'predictions/:id', to: 'predictions#purchase'
  get 'predictions/:id/accept', to: 'predictions#accept'
  get 'predictions/:id/decline', to: 'predictions#decline'
  get 'subscriptions/:id', to: 'subscriptions#purchase'

  get 'cpvls', to: 'users#panel'

  get 'faq', to: 'static_pages#faq'
  get 'contact', to: 'static_pages#contact'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Betinsider</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <%= link_to 'Bet Insider', root_path %>
                </li>
                <!--<li>-->
                	<% if user_signed_in? %>
    					<li>Welcome, <%= current_user.name %></li>
                        <li>Balance: <%= current_user.balance.round.to_s + " BM" %></li>
                        <% if current_user.is_admin? %>
                          <li><a href="cpvls" style="color: red">Admin-panel</a></li>
                        <% else %>
                          <li><a href="">Add funds</a></li>
                        <% end %>
					<% else %>
    					<li><%= link_to 'Login', new_user_session_path %></li>
    					<li><%= link_to 'Register', new_user_registration_path %></li>
					<% end %>
				<!--</li>-->
                <li>
                    <%= link_to 'Predictions', predictions_path %>
                </li>
                <li>
                    <%= link_to 'Subscriptions', subscriptions_path %>
                </li>
                <li>
                    <%= link_to 'Statistic', statistic_path %>
                </li>
                <li>
                    <%= link_to 'F.A.Q.', faq_path %>
                </li>
                <li>
                    <%= link_to 'Contacts', contact_path %>
                </li>
                <% if user_signed_in? %>
                    <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
                <% end %>


            </ul>






        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                    	<% flash.each do |name, message| %>
							<%= content_tag :div, message, class: "alert alert-#{name}" %>
						<% end %>

                        <%= yield %>

                        <!--<div class="col-md-12"><a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Скрыть/Показать Меню</a></div>-->
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>
</html>